# Generated by Django 2.2.1 on 2019-06-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20190528_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
